version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:14
    environment:
      - POSTGRES_DB=sre_tools
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=7Y5QbBYFZp
    ports:
      - "5432:5432"  # 映射 PostgreSQL 端口到主机的 5432 端口
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 数据持久化，挂载到主机目录

  redis:
    image: redis:7
    environment:
      - REDIS_PASSWORD=YvHyP7YN88
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: